version: '3.8'

services:
  web:
    build:
      context: .
      target: dev
    ports:
      - '6005:6000'
    volumes:
      - ./src:/var/app/src
      - ./package.json:/var/app/package.json
    environment:
      - POSTGRES_CONNECTION_STRING
      - GITHUB_APP_ID
      - GITHUB_APP_CLIENT_ID
      - GITHUB_APP_CLIENT_SECRET
      - GITHUB_APP_CERT

  db:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: demo
